### ISSUE TITLE
 missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by 2uanta** [mbourgey/EBI_cancer_workshop_visualization#1]
Hi,

I am trying to run your code prior to the MTL R Meetup. I got stuck by the end of the code snippets on the README page:

```
> bed1=cbind(svTable[svTable[,5]=="<TRA>",1:2],svTable[svTable[,5]=="<TRA>",2]+5)
> bed2=cbind(svTable[svTable[,5]=="<TRA>",c(4,3)],svTable[svTable[,5]=="<TRA>",3]+5)
> for (i in 1:dim(bed1)[1]) {
+ circos.link(bed1[i,1],bed1[i,2],bed2[i,1],bed2[i,2])
+ }
Error in if (degreeDiff2(theta12, theta21) <= degreeDiff2(theta22, theta21) +  : 
  missing value where TRUE/FALSE needed
>
```

I noticed that data files on github are not exactly the same as given in the README. Could it be data-dependent?

**Comment by mbourgey** [comment]
Hi,

which branch are you using actually  ?
I'll look at it.

Mathieu

---

please be sure to use my new email address:

## mathieu.bourgey@mcgill.ca

Mathieu Bourgey, PhD
Bioinformatics manager - Research and Development
Canadian Centre for Computational Genomics (C3G) - Montréal Node
McGill University and Genome Quebec Innovation Centre
http://computationalgenomics.ca/

**Comment by 2uanta** [comment]
Hi Mathieu,

I was downloading the master branch.

Quan,

**Comment by mbourgey** [comment]
Hi,

you should checkout to the  Montreal_R_UserGroup branch and use this
data and code. it is updated

let me know if it works

Thank you

Mathieu

---

please be sure to use my new email address:

## mathieu.bourgey@mcgill.ca

Mathieu Bourgey, PhD
Bioinformatics manager - Research and Development
Canadian Centre for Computational Genomics (C3G) - Montréal Node
McGill University and Genome Quebec Innovation Centre
http://computationalgenomics.ca/

**Comment by 2uanta** [comment]
Hi Mathieu,

The correct branch works. I wasn't able to test last night as Github was usually down for a while.

Thanks for your work.

Quan,

**Comment by mbourgey** [comment]
Hi Quan
you're welcome ! 
See you this evening

Mathieu
